/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ContentCardProps {
  title: string;
  description: string;
  className?: string;
}

const ContentCard: React.FC<ContentCardProps> = ({
  title,
  description,
  className = "",
}) => {
  return (
    <div className={`flex flex-col ${className}`}>
      <article className="flex flex-col grow px-10 py-20 w-full text-black bg-white rounded-[30px] shadow-[0px_1px_8px_rgba(0,0,0,0.15)] max-md:px-5 max-md:mt-6 max-md:max-w-full">
        <h2 className="self-start text-4xl font-semibold max-md:max-w-full">
          {title}
        </h2>
        <p className="mt-9 text-2xl max-md:max-w-full">{description}</p>
      </article>
    </div>
  );
};

export default ContentCard;
