/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ImageCardProps {
  src: string;
  alt: string;
  className?: string;
}

const ImageCard: React.FC<ImageCardProps> = ({ src, alt, className = "" }) => {
  return (
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className={`object-contain w-full aspect-[1.42] rounded-[30px] ${className}`}
    />
  );
};

export default ImageCard;
