/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageCard from "./ImageCard";
import ContentCard from "./ContentCard";

interface OfferDiscoveryProps {}

const OfferDiscovery: React.FC<OfferDiscoveryProps> = () => {
  const sideImages = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/0ed1d2ca1ee4fa7a892215eee59af2044c63aa4e26812b3a15489de40be7b08f?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      alt: "Offer image 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/ed95057864d7378fb86204005812a2210a5cd27d315b1092c95a733c8377ddd1?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      alt: "Offer image 2",
    },
  ];

  return (
    <section className="mt-6 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <ImageCard
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/32933544ab905eec18920246e83f87f2b1b74af823b9c5902fadd9ee28af3f10?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
          alt="Main offer image"
          className="w-3/12 max-md:ml-0 max-md:w-full"
        />
        <ContentCard
          title="Discover Offers, Loyalty Programs & More"
          description="Unlock exclusive deals, loyalty programs, and special offers. Scan the QR code to see product expiration dates, certifications, and promotions designed to enhance your shopping experience."
          className="ml-5 w-[51%] max-md:ml-0 max-md:w-full"
        />
        <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow max-md:mt-6">
            {sideImages.map((image, index) => (
              <ImageCard
                key={index}
                src={image.src}
                alt={image.alt}
                className={index > 0 ? "mt-5" : ""}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default OfferDiscovery;
