/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FeedbackContent: React.FC = () => {
  return (
    <div className="flex flex-col ml-5 w-[51%] max-md:ml-0 max-md:w-full">
      <section className="flex flex-col grow px-10 py-28 w-full text-black bg-white rounded-[30px] shadow-[0px_1px_8px_rgba(0,0,0,0.15)] max-md:px-5 max-md:py-24 max-md:mt-6 max-md:max-w-full">
        <h2 className="mr-6 text-4xl font-semibold max-md:mr-2.5 max-md:max-w-full">
          Share Feedback and Ratings
        </h2>
        <p className="mt-9 text-2xl max-md:max-w-full">
          Easily share your feedback or rate the product with just a scan. Your
          voice helps improve product quality and customer experience, giving
          you direct communication with the brand
        </p>
      </section>
    </div>
  );
};

export default FeedbackContent;
