/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ImageColumnProps {
  images: string[];
}

const ImageColumn: React.FC<ImageColumnProps> = ({ images }) => {
  return (
    <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow max-md:mt-6">
        {images.map((src, index) => (
          <img
            key={index}
            loading="lazy"
            src={src}
            alt=""
            className={`object-contain w-full aspect-[1.42] rounded-[30px] ${
              index > 0 ? "mt-5" : ""
            }`}
          />
        ))}
      </div>
    </div>
  );
};

export default ImageColumn;
