/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SingleImageColumnProps {
  src: string;
}

const SingleImageColumn: React.FC<SingleImageColumnProps> = ({ src }) => {
  return (
    <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
      <img
        loading="lazy"
        src={src}
        alt=""
        className="object-contain grow shrink-0 max-w-full aspect-[0.68] rounded-[30px] w-[302px] max-md:mt-6"
      />
    </div>
  );
};

export default SingleImageColumn;
