/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CallToAction: React.FC = () => {
  return (
    <section className="flex relative flex-wrap gap-3.5 items-center mt-8 mb-0 ml-28 text-2xl max-md:mb-2.5">
      <button className="self-stretch px-8 py-6 text-white bg-sky-400 rounded-xl max-md:px-5">
        Schedule a Demo
      </button>
      <a href="#" className="self-stretch my-auto text-white basis-auto">
        Download now
      </a>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/bbb07966233a4245eed020514a7426a62749e056638328ab21d35217c06c85b6?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
      />
    </section>
  );
};

export default CallToAction;
