/**
 * This code was generated by Builder.io.
 */
import React from "react";
export interface FAQData {
  question: string;
  answer: string;
  isOpen: boolean;
}

const FAQItem: React.FC<FAQData> = ({ question, answer, isOpen }) => {
  return (
    <div
      className={`flex flex-col w-full text-xl text-black mt-4 ${
        isOpen ? "text-white bg-sky-400" : "bg-white"
      } rounded-3xl shadow-[0px_0px_8px_rgba(0,0,0,0.15)] max-md:max-w-full`}
    >
      <div
        className={`flex flex-wrap gap-5 justify-between ${
          isOpen ? "px-4 pt-4 pb-2.5" : "px-6 py-6"
        } w-full font-${
          isOpen ? "semibold" : "medium"
        } max-md:pr-5 max-md:max-w-full`}
      >
        <div>{question}</div>
        <img
          loading="lazy"
          src={
            isOpen
              ? "https://cdn.builder.io/api/v1/image/assets/TEMP/34aee79c5e2cc11d99a93af378d29fc0fc5cec4420e5aa43e28aca094469ad04?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
              : "https://cdn.builder.io/api/v1/image/assets/TEMP/66d4e7bbeecb441e25a4284446495f021941a030c738dba9a45f05dca2098d80?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
          }
          className="object-contain shrink-0 my-auto w-8 aspect-square"
          alt=""
        />
      </div>
      {isOpen && (
        <>
          <div className="shrink-0 h-px border border-white border-solid max-md:max-w-full" />
          <div className="mt-4 px-4 pb-4 max-md:max-w-full">{answer}</div>
        </>
      )}
    </div>
  );
};

export default FAQItem;
