/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FAQItem from "./FAQItem";
import { FAQData } from "./types";

const faqData: FAQData[] = [
  {
    question: "How do smart QR codes improve product visibility?",
    answer:
      "Smart QR codes provide real-time tracking of a product's journey from manufacturing to sale. They offer full traceability, allowing companies to monitor movement through vendors and distributors.",
    isOpen: true,
  },
  {
    question: "How does this technology enhance customer engagement?",
    answer: "",
    isOpen: false,
  },
  {
    question: "Can smart QR codes prevent counterfeiting?",
    answer: "",
    isOpen: false,
  },
  {
    question: "How do smart QR codes help strengthen brand trust?",
    answer: "",
    isOpen: false,
  },
  {
    question: "How secure are smart QR codes?",
    answer: "",
    isOpen: false,
  },
  {
    question:
      "Can multiple stakeholders access the data provided by the QR code?",
    answer: "",
    isOpen: false,
  },
  {
    question: "How can I get started with smart QR codes for my products?",
    answer: "",
    isOpen: false,
  },
  {
    question: "What industries can benefit from smart QR codes?",
    answer: "",
    isOpen: false,
  },
];

const FAQSection: React.FC = () => {
  return (
    <section className="flex flex-col items-start px-20 mt-7 w-full max-md:px-5 max-md:max-w-full">
      <h1 className="text-6xl font-bold text-black max-md:max-w-full max-md:text-4xl">
        Frequently Asked Question
      </h1>
      <p className="mt-2 text-2xl text-black max-md:max-w-full">
        Unveiling the Power of Smart QR Codes
      </p>
      <div className="self-stretch mt-16 max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            {faqData.slice(0, 4).map((item, index) => (
              <FAQItem key={index} {...item} />
            ))}
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            {faqData.slice(4).map((item, index) => (
              <FAQItem key={index + 4} {...item} />
            ))}
            <div className="flex gap-1 self-end mt-9 font-semibold whitespace-nowrap">
              <span className="grow">more</span>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/6cebc7dab82a1c57384ba8c22c5ba43b160e7956e06a1c7af2aa1b5d118e32b9?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
                className="object-contain shrink-0 my-auto w-6 aspect-square"
                alt=""
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
