/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureGrid from "./FeatureGrid";

const Features: React.FC = () => {
  return (
    <section className="flex flex-col items-start px-20 mt-10 w-full max-md:px-5 max-md:max-w-full">
      <h2 className="text-6xl font-bold text-black max-md:text-4xl">
        Features
      </h2>
      <p className="mt-2 text-2xl text-black">
        Engage Customers Like Never Before!
      </p>
      <FeatureGrid />
    </section>
  );
};

export default Features;
