/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col px-20 pt-24 pb-6 mt-16 w-full bg-blue-950 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[24%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow text-xl text-white max-md:mt-10">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/b097beff868f34343c28746aae32055666ad66c2d352d9521769619843890027?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
                alt="Company logo"
                className="object-contain w-44 max-w-full aspect-[4.41]"
              />
              <div className="flex flex-col items-start pl-5 mt-10 max-md:pl-5 max-md:mt-10">
                <h3 className="text-2xl font-semibold">Call</h3>
                <p className="mt-2">90203 94857</p>
                <p className="mt-2">75849 30201</p>
                <h3 className="mt-6 text-2xl font-semibold">Mail:</h3>
                <p className="mt-2">Contact@brand.com</p>
              </div>
            </div>
          </div>
          <nav className="flex flex-col ml-5 w-[16%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col items-start mt-16 text-2xl font-semibold text-white max-md:mt-10">
              <a href="#features">Features</a>
              <a href="#testimonials" className="mt-7">
                Testimonials
              </a>
              <a href="#about" className="mt-7">
                About us
              </a>
              <a href="#contact" className="mt-7">
                Contact
              </a>
            </div>
          </nav>
          <div className="flex flex-col ml-5 w-3/5 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col self-stretch my-auto w-full text-2xl max-md:mt-10 max-md:max-w-full">
              <h3 className="self-start font-semibold text-white">
                Join for Free
              </h3>
              <form className="flex flex-wrap gap-3.5 mt-3.5 max-md:max-w-full">
                <label htmlFor="email" className="sr-only">
                  Enter your mail id
                </label>
                <input
                  type="email"
                  id="email"
                  placeholder="Enter your mail id"
                  className="grow px-5 py-3.5 text-black bg-white rounded-lg w-fit"
                  required
                />
                <button
                  type="submit"
                  className="px-11 py-3.5 font-bold text-white whitespace-nowrap bg-sky-400 rounded-xl max-md:px-5"
                >
                  Signup
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div className="flex gap-5 justify-between mt-24 text-2xl font-semibold text-white max-md:mt-10 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e61471b38681eda8d5f6caa072b4ca3da270892b7566b44513d8e518586a41d?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
          alt="Social media icons"
          className="object-contain shrink-0 max-w-full aspect-[3.66] w-[132px]"
        />
        <a href="/terms">Terms and conditions</a>
        <a href="/privacy">Privacy Policy</a>
      </div>
    </footer>
  );
};

export default Footer;
