/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex flex-wrap gap-5 justify-between px-20 py-5 w-full text-2xl text-black bg-white max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/0966a5f887208c29e823ac43e5866f183930c752d33ccadb01a1695786cdf358?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
        alt="Company logo"
        className="object-contain shrink-0 my-auto w-44 max-w-full aspect-[4.41]"
      />
      <nav className="flex flex-wrap gap-9 items-center">
        <a
          href="#home"
          className="grow self-stretch my-auto font-bold text-sky-400"
        >
          Home
        </a>
        <a href="#features" className="self-stretch my-auto whitespace-nowrap">
          Features
        </a>
        <a
          href="#testimonials"
          className="self-stretch my-auto whitespace-nowrap"
        >
          Testimonials
        </a>
        <a href="#about" className="self-stretch my-auto">
          About Us
        </a>
        <button className="px-4 py-2 font-bold text-white bg-sky-400 rounded-lg">
          Sign up
        </button>
      </nav>
    </header>
  );
};

export default Header;
