/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero: React.FC = () => {
  return (
    <section className="flex relative flex-col items-start px-8 pt-20 pb-56 w-full font-bold min-h-[780px] max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ac8e07f3cc6b91791e7f5dfadcf0c4c841bf8d0dcbcf77ac6ff21dc1b743d945?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex pl-28 relative flex-wrap gap-5 justify-between self-stretch mt-2 w-full text-4xl font-semibold text-amber-50 max-md:max-w-full">
        <h1 className="relative text-6xl text-white w-[991px] max-md:max-w-full max-md:text-4xl">
          Revolutionize Your Product Journey with Smart QR Codes
        </h1>
        <p className="flex-auto w-full">
          Empower your business with traceability, customer insights, and
          real-time product data – all in one smart solution.
        </p>
      </div>
      <div className="flex relative flex-wrap gap-3.5 items-center mt-8 mb-0 ml-28 text-2xl max-md:mb-2.5">
        <button className="self-stretch px-8 py-6 text-white bg-sky-400 rounded-xl max-md:px-5">
          Schedule a Demo
        </button>
        <a
          href="#download"
          className="self-stretch my-auto text-white basis-auto"
        >
          Download now
        </a>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/bbb07966233a4245eed020514a7426a62749e056638328ab21d35217c06c85b6?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
          alt="Download icon"
          className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
        />
      </div>
    </section>
  );
};

export default Hero;
