/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface InfoCardProps {
  title: string;
  description: string;
  className?: string;
}

const InfoCard: React.FC<InfoCardProps> = ({ title, description }) => {
  return (
    <div className="flex flex-col w-[51%] max-md:ml-0 max-md:w-full">
      <article className="flex flex-col grow px-10 py-24 w-full text-black bg-white rounded-[30px] shadow-[0px_1px_8px_rgba(0,0,0,0.15)] max-md:px-5 max-md:mt-6 max-md:max-w-full">
        <h2 className="self-start text-4xl font-semibold max-md:max-w-full">
          {title}
        </h2>
        <p className="mt-9 text-2xl max-md:max-w-full">{description}</p>
      </article>
    </div>
  );
};

export default InfoCard;
