/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface BenefitProps {
  title: string;
  description: string;
  image: string;
  imagePosition: "left" | "right";
}

const Benefit: React.FC<BenefitProps> = ({
  title,
  description,
  image,
  imagePosition,
}) => (
  <div className="mt-8 w-full max-w-[1225px] max-md:mt-10 max-md:max-w-full">
    <div
      className={`flex gap-5 ${
        imagePosition === "right" ? "flex-row-reverse" : ""
      } max-md:flex-col`}
    >
      <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
        <img
          loading="lazy"
          src={image}
          alt=""
          className="object-contain grow w-full rounded-3xl aspect-[1.41] max-md:mt-10 max-md:max-w-full"
        />
      </div>
      <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
        <div className="flex flex-col self-stretch my-auto text-black max-md:mt-10 max-md:max-w-full">
          <h3 className="text-4xl font-semibold">{title}</h3>
          <p className="mt-10 text-2xl max-md:max-w-full">{description}</p>
        </div>
      </div>
    </div>
  </div>
);

const KeyBenefits: React.FC = () => {
  const benefits: BenefitProps[] = [
    {
      title: "Complete Product Visibility",
      description:
        "Gain unmatched visibility into your product's lifecycle. From manufacturing to final sale, track every stage and actor involved. QR codes link real-time data from vendors, distributors, and sellers, so you stay informed.",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/bc705d656d52b8c0f9b44360b125d5ebd672b28e5e1da5e3e492dd22562b4a9c?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      imagePosition: "left",
    },
    {
      title: "Enhanced Customer Interaction",
      description:
        "Turn each product label into a gateway for customer interaction. Customers can scan to see product information, submit feedback, leave reviews, and even interact with your support team directly. Build lasting customer relationships through seamless communication.",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/065973f260e282949bbad7de84a3e40ff2866e039216968f3ec5ab9b6be41802?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      imagePosition: "right",
    },
    {
      title: "Real-Time Insights and Performance Monitoring",
      description:
        "Monitor key performance indicators (KPIs) like customer feedback, reviews, and product ratings. Access real-time statistics, see product performance on a map, and visualize your customer base in detail—all in one place.",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/aceed123d017cebcf8fc4bf83b142f71700a2b70bc1b61e751dac736e30acc21?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      imagePosition: "left",
    },
    {
      title: "Strengthened Brand Trust and Support Services",
      description:
        "Your unique QR code not only authenticates products but also connects customers to your support services. Reduce counterfeit risks and enhance post-sale support while building brand loyalty through transparency.",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/aa915916ee4706815ed1772676677995d472bda74153c852d33d7b89f05a88af?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      imagePosition: "right",
    },
  ];

  return (
    <section className="flex flex-col px-20 mt-8 w-full max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h2 className="mt-20 text-6xl font-bold text-black max-md:mt-10 max-md:text-4xl">
        Key Benefits
      </h2>
      <h3 className="mt-2 text-4xl font-semibold text-neutral-700 max-md:max-w-full">
        For Product Companies
      </h3>
      {benefits.map((benefit, index) => (
        <Benefit key={index} {...benefit} />
      ))}
    </section>
  );
};

export default KeyBenefits;
