/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import Features from "./Features";
import HowItWorks from "./HowItWorks";
import KeyBenefits from "./KeyBenefits";
import ConsumerBenefits from "./ConsumerBenefits";
import Testimonials from "./Testimonials";
import FAQ from "./FAQSection";
import Footer from "./Footer";

const SmartQRCodePage: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <Hero />
      <Features />
      <HowItWorks />
      <KeyBenefits />
      <ConsumerBenefits />
      <Testimonials />
      <div className="flex flex-col justify-center px-20 py-12 mt-16 w-full bg-white shadow-[0px_0px_6px_rgba(0,0,0,0.15)] max-md:px-5 max-md:mt-10 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/52d7974dc7360c7bcdd9a255fc3d14f3f6c1fb6e9ad30a451f91d3b4d1fe5d4e?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
          alt="Product showcase"
          className="object-contain aspect-[19.23] w-[1278px] max-md:max-w-full"
        />
      </div>
      <FAQ />
      <Footer />
    </div>
  );
};

export default SmartQRCodePage;
