/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import CallToAction from "./CallToAction";

interface SmartQRCodeProps {
  title: string;
  description: string;
}

const SmartQRCode: React.FC<SmartQRCodeProps> = ({ title, description }) => {
  return (
    <main className="flex relative flex-col items-start px-8 pt-20 pb-56 w-full font-bold min-h-[780px] max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ac8e07f3cc6b91791e7f5dfadcf0c4c841bf8d0dcbcf77ac6ff21dc1b743d945?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <Header title={title} description={description} />
      <CallToAction />
    </main>
  );
};

export default SmartQRCode;
