/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TestimonialProps {
  image: string;
  name: string;
  content: string;
}

const Testimonial: React.FC<TestimonialProps> = ({ image, name, content }) => (
  <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
    <div className="flex flex-col grow items-center px-6 py-7 w-full bg-white rounded-3xl shadow-[0px_4px_15px_rgba(0,0,0,0.1)] max-md:px-5 max-md:mt-6 max-md:max-w-full">
      <img
        loading="lazy"
        src={image}
        alt={`${name}'s profile`}
        className="object-contain max-w-full rounded-full aspect-square w-[100px]"
      />
      <h3 className="mt-5 text-3xl font-semibold text-black">{name}</h3>
      <p className="self-stretch mt-5 text-xl text-neutral-700 max-md:max-w-full">
        {content}
      </p>
    </div>
  </div>
);

const Testimonials: React.FC = () => {
  const testimonials: TestimonialProps[] = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ca8d22e00600504af0e57f8ff407b4a53796874e001e164f8be4666959dc4943?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      name: "Emily Johnson",
      content:
        "Since implementing [Your Brand Name]'s QR code solution, we've seen a huge improvement in customer engagement. The real-time feedback and product verification features have greatly increased trust in our brand.",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/49feea45f96f6fa796df8c48c2c346fe06af21ef30e28e0e10ffd80ab063b937?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      name: "David Lee",
      content:
        "[Your Brand Name] gave us the tools we needed to optimize our product tracking process. The smart QR codes provided us with instant data and insights, helping us streamline operations and boost customer satisfaction.",
    },
  ];

  return (
    <section className="flex flex-col items-start px-20 mt-20 w-full max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h3 className="self-start mt-20 text-4xl font-semibold text-black max-md:mt-10">
        Testimonials
      </h3>
      <h2 className="self-start mt-2 text-6xl font-bold text-black max-md:max-w-full max-md:text-4xl">
        What Our Clients Says
      </h2>
      <div className="mt-9 w-full max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {testimonials.map((testimonial, index) => (
            <Testimonial key={index} {...testimonial} />
          ))}
        </div>
      </div>
      <div className="flex gap-5 justify-between self-center mt-14 max-w-full w-[136px] max-md:mt-10">
        <div className="flex shrink-0 w-4 h-4 bg-sky-400 rounded-full" />
        <div className="flex shrink-0 w-4 h-4 rounded-full border-2 border-sky-400 border-solid" />
        <div className="flex shrink-0 w-4 h-4 rounded-full border-2 border-sky-400 border-solid" />
        <div className="flex shrink-0 w-4 h-4 rounded-full border-2 border-sky-400 border-solid" />
      </div>
    </section>
  );
};

export default Testimonials;
