/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageCard from "./ImageCard";
import InfoCard from "./InfoCard";

interface TransparentProductInfoProps {}

const TransparentProductInfo: React.FC<TransparentProductInfoProps> = () => {
  const sideImages = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/dec7c5746bfc429a93e9d09fd677b1b364236f577de7e7554db13f6549614f10?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      alt: "Product information display",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/251a833b07768d12c58e70dd97fa71aae31aeaf63024e4a019647ee2515f2e08?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440",
      alt: "QR code scanning demonstration",
    },
  ];

  return (
    <section className="mt-16 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <ImageCard
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/875a7a3c64a6ee2c8fdac518efdd94ae81783ddf57cce22533e7c8f35685cd2e?placeholderIfAbsent=true&apiKey=99fc076702324161981b628a0ba62440"
          alt="Transparent product information concept"
          className="w-3/12 max-md:w-full"
        />
        <InfoCard
          title="Transparent Product Information"
          description="Get access to detailed product information right at your fingertips. Scan the QR code to see data provided by manufacturers, vendors, distributors, and sellers. Ensure the product you're buying meets your expectations."
          className="ml-5 w-[51%] max-md:ml-0 max-md:w-full"
        />
        <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow max-md:mt-6">
            {sideImages.map((image, index) => (
              <ImageCard
                key={index}
                src={image.src}
                alt={image.alt}
                className={index > 0 ? "mt-5" : ""}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default TransparentProductInfo;
